### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery-operator#11]
Let's cut an initial release.

## Prerequisites

- [x] Container image repo (#1) 
- [x] Use new NFD image repo (and version) (#9)
- [x] Document release process (#10)

## Checklist
- [x] File [a new issue](https://github.com/kubernetes-sigs/node-feature-discovery-operator/issues/new) to propose a new release. Copy this checklist into the issue description
- [ ] Add a changelog section in the issue description, capturing changes since the previous release
- [ ] An OWNER runs `git tag -s $VERSION` and inserts the changelog into the tag description
- [ ] An OWNER pushes the tag with `git push $VERSION` - this will trigger prow to build and publish a staging container image `gcr.io/k8s-staging-nfd/node-feature-discovery-operator:$VERSION`
- [ ] Do final release verification on the staging image
- [ ] Submit a PR against [k8s.io](https://github.com/kubernetes/k8s.io), updating `k8s.gcr.io/images/k8s-staging-nfd/images.yaml`, in order to promote the container image to production
- [ ] Wait for the PR to be merged and verify that the image (`k8s.gcr.io/nfd/node-feature-discovery-operator:$VERSION`) is available
- [ ] Write the change log into the [Github release info](https://github.com/kubernetes-sigs/node-feature-discovery-operator/releases).
- [ ] Add a link to the tagged release in this issue
- [ ] Send an announcement email to `kubernetes-dev@googlegroups.com` with the subject `[ANNOUNCE] node-feature-discovery-operator $VERSION is released`
- [ ] Add a link to the release announcement email in this issue
- [ ] Close this issue

## Changelog

This is the first release of Node Feature Discovery Operator. It has basic functionality of operating Node Feature Discovery v0.6.0, running nfd-master and nfd-worker as daemonsets in the cluster.

**Comment by ArangoGutierrez** [comment]
Check Container image repo (#1)

**Comment by ArangoGutierrez** [comment]
Check  Use new NFD image repo (and version) #9

**Comment by marquiz** [comment]
👍   I marked those^ done in the checklist above

**Comment by marquiz** [comment]
Changelog is missing above. Feel free to add one 😉

**Comment by marquiz** [comment]
@ArangoGutierrez @zvonkok should we proceed with this(?)

I added a minimal "changelog" above...

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/35 
We will cut the first release to be compatible with kube 1.19

**Comment by ArangoGutierrez** [comment]
Release v0.2.0 is being cut today
